UI/Controllers/EditUserFullDetailsController.cs
using DomainModel.EditUserFullDetails;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Services.RegisteredJobSeekers;

namespace UI.Controllers
{
    [Authorize(Roles = "Job Seeker, Admin, Super Admin")]
    public class EditUserFullDetailsController : Controller
    {
        private readonly IEditUserFullDetailsServices _EditUserFullDetailServices;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EditUserFullDetailsController(IEditUserFullDetailsServices EditUserFullDetailsServices, IWebHostEnvironment webHostEnvironment)
        {
            _EditUserFullDetailServices = EditUserFullDetailsServices;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index(int id)
        {
            EditUserFullDetails model = new EditUserFullDetails();
            model.UserId = id;
            return View(model);
        }

        [HttpGet]
        public IActionResult GetUserDetails(int id)
        {
            var result = _EditUserFullDetailServices.GetUserFullDetails(id).ToList();
            return Ok(result);
        }

        [HttpGet]
        public IActionResult GetBachelors()
        {
            var result = _EditUserFullDetailServices.GetBachelorsList().ToList();
            return Ok(result);
        }

        [HttpGet]
        public IActionResult GetMasters()
        {
            var result = _EditUserFullDetailServices.GetMastersList().ToList();
            return Ok(result);
        }

        [HttpGet]
        public IActionResult GetCountry()
        {
            var result = _EditUserFullDetailServices.GetCountryList().ToList();
            return Ok(result);
        }

        [HttpGet]
        public IActionResult GetState(string country)
        {
            var result = _EditUserFullDetailServices.GetStateList(country).ToList();
            return Ok(result);
        }

        [HttpGet]
        public IActionResult GetCity(string state)
        {
            var result = _EditUserFullDetailServices.GetCityList(state).ToList();
            return Ok(result);
        }

        [HttpPost]
        public IActionResult UpdateUserDetails(EditUserFullDetails userDetails)
        {
            if (TempData["ImagePath"] != null)
            {
                userDetails.ProfilePicture = "/" + TempData["ImagePath"].ToString();
            }
            else
            {
                userDetails.ProfilePicture = userDetails.ProfilePictureUrl;
            }

            if (TempData["ResumePath"] != null)
            {
                userDetails.Resume = "/" + TempData["ResumePath"].ToString();
            }
            else
            {
                userDetails.Resume = userDetails.ResumeUrl;
            }

            string result = string.Empty;
            result = _EditUserFullDetailServices.UpdateProfileDetails(userDetails);
            userDetails.Response = result;
            return Ok(userDetails);
        }


        [HttpPost]
        public async Task<IActionResult> UploadProfilePicture(IFormFile profilePicture)
        {
            if (profilePicture != null && profilePicture.Length > 0)
            {
                try
                {
                    var fileName = "UserProfile/" + $"{Guid.NewGuid().ToString()}{Path.GetExtension(profilePicture.FileName)}";
                    var filePath = Path.Combine(_webHostEnvironment.WebRootPath, fileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await profilePicture.CopyToAsync(fileStream);
                    }
                    TempData["ImagePath"] = fileName;
                    return Json(new { success = true, url = $"/{fileName}" });
                }
                catch (Exception ex)
                {
                    return Json(new { success = false, error = ex.Message });
                }
            }
            return Json(new { success = false, error = "No image was uploaded." });
        }

        public async Task<IActionResult> RemoveProfilePicture(string profilePicture)
        {
            if (profilePicture != null && profilePicture.Length > 0)
            {
                try
                {
                    var fileName = profilePicture;
                    TempData["ImagePath"] = fileName;
                    return Json(new { success = true, url = $"/{fileName}" });
                }
                catch (Exception ex)
                {
                    return Json(new { success = false, error = ex.Message });
                }
            }
            return Json(new { success = false, error = "Failed" });
        }

        [HttpPost]
        public async Task<IActionResult> UploadResume(IFormFile resume)
        {
            if (resume != null && resume.Length > 0)
            {
                try
                {
                    var fileName = "UserResume/" + $"{Guid.NewGuid().ToString()}{Path.GetExtension(resume.FileName)}";
                    var filePath = Path.Combine(_webHostEnvironment.WebRootPath, fileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await resume.CopyToAsync(fileStream);
                    }
                    TempData["ResumePath"] = fileName;
                    return Json(new { success = true, url = $"/{fileName}" });
                }
                catch (Exception ex)
                {
                    return Json(new { success = false, error = ex.Message });
                }
            }
            return Json(new { success = false, error = "No image was uploaded." });
        }
    }
}

UI/Controllers/UserDashboardController.cs
using DomainModel.Jobs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;
using Services.AppliedJobs;
using Services.Jobs;
using Microsoft.AspNetCore.Mvc.Rendering;
using DomainModel.Users;
using static SkiaSharp.HarfBuzz.SKShaper;
using Repository.AppliedJobs;

namespace UI.Controllers
{
    [Authorize(Roles = "Job Seeker, Admin, Super Admin")]
    public class UserDashboardController : Controller
    {

        private readonly IAppliedJobsServices _appliedJobsServices;
        private readonly IJobServices _jobServices;
        public UserDashboardController(IAppliedJobsServices appliedJobsServices, IJobServices jobServices)
        {
            _appliedJobsServices = appliedJobsServices;
            _jobServices = jobServices;
        }



        public IActionResult MyProfile() /*Used as a home page controller*/
        {
            var jobs = _jobServices.GetJobsForHomePage();
            var activeJobs = jobs.Where(job => job.IsActive).ToList();

            return View(activeJobs);
        }
        //Job fetching 
        public IActionResult AllJobs()
        {
            var jobs = _jobServices.GetJobsForHomePage();
            var jobTypes = _jobServices.GetMasterValuesByCategory("Job Type");
            var jobModes = _jobServices.GetMasterValuesByCategory("Job Mode");

            ViewBag.JobTypes = new SelectList(jobTypes, "Id", "Value");
            ViewBag.JobModes = new SelectList(jobModes, "Id", "Value");
            return View(jobs);
        }
        public IActionResult Details(int id)
        {
            var JobDetails = _jobServices.GetJobByIdView(id);

            if (JobDetails == null)
            {

                return NotFound();
            }

            return View(JobDetails);
        }
        //end


        public IActionResult AboutUs()
        {
            return View();
        }
        public IActionResult ContactUs()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> CreateAppliedJob(int job_Id)  /* Applied job by user function  */
        {
            int User_Id = Convert.ToInt32(User.FindFirst(claim => claim.Type == System.Security.Claims.ClaimTypes.NameIdentifier)?.Value);
            bool count = _appliedJobsServices.HasUserApplied(User_Id, job_Id);
            if (count)
            {
                return Ok(new { response = count, status1 = true, responseof = "HasUserApplied" });
            }
            else
            {

                if (job_Id != 0)
                {
                    
                    bool result = await _appliedJobsServices.IsUserResumeUploaded(User_Id);
                    if (result)
                    {
                        var response = _appliedJobsServices.CreateAppliedJob(User_Id, job_Id);
                        return Ok(new { response = response, status = true, responseof = "Job Applied" });
                    }
                    else
                    {
                        return Ok(new { response = result, status = false, responseof = "Resume Required", userid = User_Id });
                    }
                }
            }
                    
            return BadRequest(new { status = false, responseof = "" });
        }
        public IActionResult AppliedJobs(int id)
        {
            ViewBag.UserId = id;
            return View();
        }
        public async Task<IActionResult> GetMyAppliedJobs(int id) /* User Applied job */
        {
            return Json(await _appliedJobsServices.MyAppliedJobs(id));
        }


        public IActionResult Logout()
        {
            return View();
        }

    }
}

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  (i2e Job Portal)</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Kodchasan:ital,wght@0,400;0,600;0,700;1,500;1,700&family=Montserrat:wght@500&family=Poppins:wght@300;400;600;700;800&family=Roboto&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="~/css/userlayout.css">

    <style>
        

            
            
    </style>
</head>
<body>
    <header>
        <div class="container-fluid">
        <div class="col-lg-12 menu-contains">
        <nav class="navbar navbar-expand-lg bg-white navbar-light">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/i2e_JobPortal_Logo.jpg" alt="i2e Logo" style="width:155px;">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav ms-auto">

                        <li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Jobs">Jobs</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        @*<li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Signup">Signup</a>
                        </li>*@
                        
                    </ul>
                </div>

            </div>
        </nav>
        </div>
        </div>

        
    </header>
   @* <div class="container">*@

        @RenderBody()

   @* </div>*@

    <footer class="border-top footer text-muted" style="background-color:#202020">
        <div class="container">

            <div class="container-fluid">
                <div class="row footerBackground">
                    <div class="col-sm footerLogoSection">
                        <div class="col-sm-1" style="text-align: left;">
                            <img src="~/Images/i2e_Logo_White.png" alt="i2e Logo" style="width:60px; float: left;" />
                        </div>
                        <div class="col-sm-9" style="float: right;">
                            <small style="font-size:10px;">i2e consulting named among the fastest growing private companies in the US (2018 Inc. 5000), a Microsoft Gold partner has been delivering tailored solutions to Fortune 100 companies for over a decade.</small>
                        </div>
                        <div class="col-sm-2 ms-4">
                            <div class="web-logoicon d-flex justify-content-around">
                                <div class="fb-icon"><i class="fa-brands fa-facebook"></i></div>
                                <div class="insta-icon"><i class="fa-brands fa-instagram"></i></div>
                                <div class="insta-icon"><i class="fa-brands fa-linkedin-in"></i></div>
                                <div class="insta-icon"><i class="fa-brands fa-twitter"></i></div>
                            </div>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
    </footer> 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)



    <script type="text/javascript">
        $(function ($) {
            let url = window.location.href;
            $('nav ul li a').each(function () {
                if (this.href === url) {
                    $(this).attr('class', 'active');
                }
            });
        });
    </script>
</body>
</html>

UI/Views/Shared/_LayoutUserDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] (i2e Job Portal)</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Kodchasan:ital,wght@0,400;0,600;0,700;1,500;1,700&family=Montserrat:wght@500&family=Poppins:wght@300;400;600;700;800&family=Roboto&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="~/css/userdahboardlayout.css">
    <style>
         


    </style>
</head>
<body>
    <header>

        <div class="col-lg menu-contains">
        <nav class="navbar navbar-expand-lg bg-white navbar-light">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/i2e_JobPortal_Logo.jpg" alt="i2e Logo" style="width:155px;">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav ms-auto">

                                            
                        <li class="nav-item px-2">
                                <a class="nav-link" asp-area="" asp-controller="UserDashboard" asp-action="MyProfile">Home</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="UserDashboard" asp-action="AllJobs">Jobs</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="UserDashboard" asp-action="AppliedJobs" asp-route-id="@User.FindFirst(claim=>claim.Type==System.Security.Claims.ClaimTypes.NameIdentifier)?.Value">Applied Jobs</a>
                        </li>

                           @* <a class="nav-link" asp-area="" asp-controller="UserDashboard" asp-action="AppliedJobs">Applied Jobs</a>
                        </li>   
*@
                        <li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="UserDashboard" asp-action="AboutUs">About Us</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>

                        <li class="nav-item dropdown nav-drop">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                                <img id="profileImage" src="#" alt="Profile Picture" style="width: 40px; height: 40px; border-radius: 10px; border: 1px solid #202020;" />
                                <span class="badge rounded-pill" style="background-color: white; color: #202020;">
                                    <span id="firstNameSpan"></span><br />
                                    @User.FindFirst(claim=>claim.Type==System.Security.Claims.ClaimTypes.Role)?.Value
                                </span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-end">
                                <a asp-controller="EditUserFullDetails" asp-action="Index" asp-route-id="@User.FindFirst(claim=>claim.Type==System.Security.Claims.ClaimTypes.NameIdentifier)?.Value" class="dropdown-item">Manage Profile Details</a>
                                <div class="dropdown-divider"></div>
                                <a asp-controller="Account" asp-action="Logout" class="dropdown-item">Logout</a>
                            </div>
                        </li>

                                           
                    </ul>
                </div>

            </div>
        </nav>
        </div>

        
    </header>
    @*<div class="container">*@

        @RenderBody()
        @*
    </div>*@

    <footer class="border-top footer text-muted" style="background-color:#202020">
        <div class="container">

            <div class="container-fluid">
                <div class="row footerBackground">
                    <div class="col-sm footerLogoSection">
                        <div class="col-sm-1" style="text-align: left;">
                            <img src="~/Images/i2e_Logo_White.png" alt="i2e Logo" style="width:60px; float: left;" />
                        </div>
                        <div class="col-sm-9" style="float: right;">
                            <small style="font-size:10px; font-weight: 400;">i2e consulting named among the fastest growing private companies in the US (2018 Inc. 5000), a Microsoft Gold partner has been delivering tailored solutions to Fortune 100 companies for over a decade.</small>
                        </div>
                        <div class="col-sm-2 ms-4">
                            <div class="web-logoicon d-flex justify-content-around">
                                <div class="fb-icon"><i class="fa-brands fa-facebook"></i></div>
                                <div class="insta-icon"><i class="fa-brands fa-instagram"></i></div>
                                <div class="insta-icon"><i class="fa-brands fa-linkedin-in"></i></div>
                                <div class="insta-icon"><i class="fa-brands fa-twitter"></i></div>
                            </div>
                        </div>
                    </div>



                </div>
            </div>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>

        $(() => {
            function LoadRecords() {
                var userId = @User.FindFirst(claim=>claim.Type==System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
                $.ajax({
                    url: "/EditUserFullDetails/GetUserDetails",
                    method: "GET",
                    data: { "id": userId },
                    success: function (ResponseData) {
                        const user = ResponseData[0];
                        console.log(user.ProfilePicture);
                        console.log(user.FirstName)
                        const profileImageElement = document.getElementById("profileImage");
                        profileImageElement.src = user.ProfilePicture; // Set the src attribute
                        if (user.ProfilePicture == null || user.ProfilePicture == "") {
                            user.ProfilePicture = "/UserProfile/DefaultProfileJobSeeker.png"; // Set the src attribute
                        }
                        profileImageElement.src = user.ProfilePicture;

                        const firstNameSpan = document.getElementById("firstNameSpan");
                        firstNameSpan.textContent = "Hi " + user.FirstName; // Set the content of the span
                    },
                    error: function (err) {
                        alert(err);
                    }

                })
            }

            LoadRecords();


        });
    </script>


    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>

    <script type="text/javascript">
        $(function ($) {
            let url = window.location.href;
            $('nav ul li a').each(function () {
                if (this.href === url) {
                    $(this).attr('class', 'active');
                }
            });
        });
    </script>

</body>
</html>